name: Deploy Assets

on:
  push:
    branches:
      - main # Remplacez "main" par le nom de votre branche de production si nécessaire.

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Utilisez Node.js 16 au lieu de 14.

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run prod

    # Ajoutez ici les étapes supplémentaires pour déployer les assets construits sur votre serveur ou votre service d'hébergement.
